# -*- coding: utf-8 -*-
"""cm3-1_exam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SB0X2GxTytvRjZ9igtDjsvxyiMmEwxqm

# Exam 0: Basic Python, Functions, Lists, Strings, and Files

## EXERCISE 1: A Simple Calculator

Here is a fun little calculator which exercises what you have learnt so far.

It has only 4 operations - Addition, Subtraction, Multiplication and Divison

Look up the documentation of the input function on google.
"""

print("Select operation\n")
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")

# Something NEW: Take input from the user
choice = input("\nEnter choice(1/2/3/4): ")

# We convert the input to a floating-point(or real) number.

num1 = float(input("\nEnter first number: "))
num2 = float(input("\nEnter second number: "))

if choice == '1':
    # your code here
	print(f"\nResult: {num1} + {num2} = {num1 + num2}")

elif choice == '2':
    print(f"\nResult: {num1} - {num2} = {num1 - num2}")

elif choice == '3':
    print(f"\nResult: {num1} * {num2} = {num1 * num2}")

elif choice == '4':
    if num2 != 0:
        print(f"\nResult: {num1} / {num2} = {num1 / num2}")
    else:
        print("\nError: Division by zero is not allowed.")

else:
    print("\nInvalid input! Please enter a valid operation number (1/2/3/4).")

"""## EXERCISE 2: Parsing a speech

The text of  Martin Luther King Jr.'s great speech, "I have a dream" is included below. Count the number of times each word repeats. You will have to lowercase all letters using `lower` method on strings, remove punctuation, which can be defined as all the characters in the string; `string.punctuation`
"""

speech = """
Five score years ago, a great American, in whose symbolic shadow we
stand signed the Emancipation Proclamation.  This momentous decree
came as a great beacon light of hope to millions of Negro slaves who
had been seared in the flames of withering injustice.  It came as a
joyous daybreak to end the long night of captivity.

	But one hundred years later, we must face the tragic fact that
the Negro is still not free.  One hundred years later, the life of the
Negro is still sadly crippled by the manacles of segregation and the
chains of discrimination.  One hundred years later, the Negro lives on
a lonely island of poverty in the midst of a vast ocean of material
prosperity.  One hundred years later, the Negro is still languishing
in the corners of American society and finds himself an exile in his
own land.  So we have come here today to dramatize an appalling
condition.

	In a sense we have come to our nation's capital to cash a
check.  When the architects of our republic wrote the magnificent
words of the Constitution and the declaration of Independence, they
were signing a promissory note to which every American was to fall
heir.  This note was a promise that all men would be guarranteed the
inalienable rights of life, liberty, and the pursuit of happiness.

	It is obvious today that America has defaulted on this
promissory note insofar as her citizens of color are concerned.
Instead of honoring this sacred obligation, America has given the
Negro people a bad check which has come back marked "insufficient
funds." But we refuse to believe that the bank of justice is bankrupt.
We refuse to believe that there are insufficient funds in the great
vaults of opportunity of this nation.  So we have come to cash this
check -- a check that will give us upon demand the riches of freedom
and the security of justice.  We have also come to this hallowed spot
to remind America of the fierce urgency of now.  This is no time to
engage in the luxury of cooling off or to take the tranquilizing drug
of gradualism.  Now is the time to rise from the dark and desolate
valley of segregation to the sunlit path of racial justice.  Now is
the time to open the doors of opportunity to all of God's children.
Now is the time to lift our nation from the quicksands of racial
injustice to the solid rock of brotherhood.

	It would be fatal for the nation to overlook the urgency of
the moment and to underestimate the determination of the Negro.  This
sweltering summer of the Negro's legitimate discontent will not pass
until there is an invigorating autumn of freedom and equality.
Nineteen sixty-three is not an end, but a beginning.  Those who hope
that the Negro needed to blow off steam and will now be content will
have a rude awakening if the nation returns to business as usual.
There will be neither rest nor tranquility in America until the Negro
is granted his citizenship rights.  The whirlwinds of revolt will
continue to shake the foundations of our nation until the bright day
of justice emerges.

	But there is something that I must say to my people who stand
on the warm threshold which leads into the palace of justice.  In the
process of gaining our rightful place we must not be guilty of
wrongful deeds.  Let us not seek to satisfy our thirst for freedom by
drinking from the cup of bitterness and hatred.

	We must forever conduct our struggle on the high plane of
dignity and discipline.  We must not allow our creative protest to
degenerate into physical violence.  Again and again we must rise to
the majestic heights of meeting physical force with soul force.  The
marvelous new militancy which has engulfed the Negro community must
not lead us to distrust of all white people, for many of our white
brothers, as evidenced by their presence here today, have come to
realize that their destiny is tied up with our destiny and their
freedom is inextricably bound to our freedom.  We cannot walk alone.

	And as we walk, we must make the pledge that we shall march
ahead.  We cannot turn back.  There are those who are asking the
devotees of civil rights, "When will you be satisfied?"  We can never
be satisfied as long as our bodies, heavy with the fatigue of travel,
cannot gain lodging in the motels of the highways and the hotels of
the cities.  We cannot be satisfied as long as the Negro's basic
mobility is from a smaller ghetto to a larger one.  We can never be
satisfied as long as a Negro in Mississippi cannot vote and a Negro in
New York believes he has nothing for which to vote.  No, no, we are
not satisfied, and we will not be satisfied until justice rolls down
like waters and righteousness like a mighty stream.

	I am not unmindful that some of you have come here out of
great trials and tribulations.  Some of you have come fresh from
narrow cells.  Some of you have come from areas where your quest for
freedom left you battered by the storms of persecution and staggered
by the winds of police brutality.  You have been the veterans of
creative suffering.  Continue to work with the faith that unearned
suffering is redemptive.

	Go back to Mississippi, go back to Alabama, go back to
Georgia, go back to Louisiana, go back to the slums and ghettos of our
northern cities, knowing that somehow this situation can and will be
changed.  Let us not wallow in the valley of despair.

	I say to you today, my friends, that in spite of the
difficulties and frustrations of the moment, I still have a dream.  It
is a dream deeply rooted in the American dream.

	I have a dream that one day this nation will rise up and live
out the true meaning of its creed: "We hold these truths to be
self-evident: that all men are created equal."

	I have a dream that one day on the red hills of Georgia the
sons of former slaves and the sons of former slaveowners will be able
to sit down together at a table of brotherhood.

	I have a dream that one day even the state of Mississippi, a
desert state, sweltering with the heat of injustice and oppression,
will be transformed into an oasis of freedom and justice.

	I have a dream that my four children will one day live in a
nation where they will not be judged by the color of their skin but by
the content of their character.

	I have a dream today.

	I have a dream that one day the state of Alabama, whose
governor's lips are presently dripping with the words of interposition
and nullification, will be transformed into a situation where little
black boys and black girls will be able to join hands with little
white boys and white girls and walk together as sisters and brothers.

	I have a dream today.

I have a dream that one day every valley shall be exalted, every hill
and mountain shall be made low, the rough places will be made plain,
and the crooked places will be made straight, and the glory of the
Lord shall be revealed, and all flesh shall see it together.

	This is our hope.  This is the faith with which I return to
the South.  With this faith we will be able to hew out of the mountain
of despair a stone of hope.  With this faith we will be able to
transform the jangling discords of our nation into a beautiful
symphony of brotherhood.  With this faith we will be able to work
together, to pray together, to struggle together, to go to jail
together, to stand up for freedom together, knowing that we will be
free one day.

	This will be the day when all of God's children will be able
to sing with a new meaning, "My country, 'tis of thee, sweet land of
liberty, of thee I sing.  Land where my fathers died, land of the
pilgrim's pride, from every mountainside, let freedom ring."

	And if America is to be a great nation this must become true.
So let freedom ring from the prodigious hilltops of New Hampshire.
Let freedom ring from the mighty mountains of New York.  Let freedom
ring from the heightening Alleghenies of Pennsylvania!

	Let freedom ring from the snowcapped Rockies of Colorado!

	Let freedom ring from the curvaceous peaks of California!

	But not only that; let freedom ring from Stone Mountain of
Georgia!

	Let freedom ring from Lookout Mountain of Tennessee!

	Let freedom ring from every hill and every molehill of
Mississippi.  From every mountainside, let freedom ring.

	When we let freedom ring, whem we let it ring from every
village and every hamlet, from every state and every city, we will be
able to speed up that day when all of God's children, black men and
white men, Jews and Gentiles, Protestants and Catholics, will be able
to join hands and sing in the words of the old Negro spiritual, "Free
at last! free at last! thank God Almighty, we are free at last!"
"""

"""Here is some code to help you along."""
"""Here is some code to help you along."""

import string
from collections import Counter

# Function to remove punctuation from text
def strip_punctuation(text):
    """Removes punctuation from the text."""
    return text.translate(str.maketrans('', '', string.punctuation))

# Function to process text into lowercase words
def make_words(text):
    """Converts text to lowercase and splits into words."""
    text = text.lower()  # Convert to lowercase
    text = strip_punctuation(text)  # Remove punctuation
    words = text.split()  # Split into words
    return words

# Function to count occurrences of each word
def count_occurrences(words):
    """Counts occurrences of each word and returns a dictionary."""
    return dict(Counter(words))

# Example usage with test strings
test_str = 'Gfg, is best: for ! Geeks ;'
cleaned_str = strip_punctuation(test_str)
print("Processed String:", cleaned_str)

text = """
Hello this is:
a second Line.
And a third
"""
text = strip_punctuation(text)
print("Processed Text:", text)

words = []
for line in text.split("\n"):
    words += line.strip().split()

# Count occurrences of words
word_counts = count_occurrences(words)
print("Word Frequency:", word_counts)

"""Now apply this to MLK Jr.'s speech to determine the most used word."""

# Sample speech (Replace with full speech)
speech = """ 
Five score years ago, a great American, in whose symbolic shadow we stand today, signed the Emancipation Proclamation...
"""  # Replace this with the full speech content

# Process MLK speech
speech_words = make_words(speech)
speech_word_counts = count_occurrences(speech_words)

# Find the most used word
most_common_word, most_common_count = max(speech_word_counts.items(), key=lambda x: x[1])

print(f"MLK Jr.'s most used word: '{most_common_word}' appeared {most_common_count} times.")
